// src/components/resume/preview/SkillsSection.svelte
<script lang="ts">
  import type { Skill } from '@/types/resume';
  import { groupSkillsByCategory } from '@/lib/skills-utils';

  interface Props {
    skills: Skill[];
  }

  let { skills }: Props = $props();

  const hasContent = $derived(
    skills && skills.some((skill) => skill.name)
  );

  const groupedSkills = $derived(
    hasContent ? groupSkillsByCategory(skills) : {}
  );

  const hasGroupedSkills = $derived(
    Object.keys(groupedSkills).length > 0
  );
</script>

{#if hasContent && hasGroupedSkills}
  <section>
    <h2 class="mb-2 border-b border-border pb-1 text-base font-bold uppercase text-primary">
      SKILLS
    </h2>
    {#each Object.entries(groupedSkills) as [category, categorySkills]}
      <div class="mb-4">
        <h3 class="mb-2 text-sm font-bold uppercase text-primary">
          {category}
        </h3>
        <div class="flex flex-wrap gap-2 pt-2">
          {#each categorySkills as skill}
            {#if skill.name}
              <span class="rounded-full border border-white bg-black px-2 py-1 text-xs font-medium text-white dark:border-black dark:bg-white dark:text-black">
                {skill.name}
              </span>
            {/if}
          {/each}
        </div>
      </div>
    {/each}
  </section>
{/if}

// src/components/resume/preview/skills-section.tsx
import { Skill } from "@/types/resume";

interface SkillsSectionProps {
  skills: Skill[];
}

// Helper function to group skills by category
const groupSkillsByCategory = (skills: Skill[]) => {
  const grouped: { [category: string]: Skill[] } = {};
  skills.forEach(skill => {
    if (skill.name) { // Ensure skill has a name
      const category = skill.category || "General Skills";
      if (!grouped[category]) {
        grouped[category] = [];
      }
      grouped[category].push(skill);
    }
  });
  return grouped;
};

export function SkillsSection({ skills }: SkillsSectionProps) {
  if (!skills.some((skill) => skill.name)) {
    return null;
  }

  const groupedSkills = groupSkillsByCategory(skills);

  return (
    <section>
      <h2 className="text-base font-bold text-primary uppercase mb-2 pb-1 border-b border-border">SKILLS</h2>
      {Object.entries(groupedSkills).map(([category, categorySkills]) => (
        <div key={category} className="mb-4">
          <h3 className="text-sm font-bold uppercase text-primary mb-2">{category}</h3>
          <div className="flex flex-wrap gap-2 pt-2">
            {categorySkills.map(
              (skill) => (
                skill.name && (
                  <span
                    key={skill.id}
                    className="px-2 py-1 rounded-full border text-xs font-medium bg-black text-white border-white dark:bg-white dark:text-black dark:border-black"
                  >
                    {skill.name}
                  </span>
                )
              ),
            )}
          </div>
        </div>
      ))}
    </section>
  );
}
